"""Reporter Agent – tổng hợp kết quả, lưu test cases + report JSON/Markdown."""

from __future__ import annotations

import json
from datetime import datetime
from pathlib import Path
from typing import Any

from rich.console import Console
from rich.panel import Panel
from rich.table import Table

from agents.state import AgentState
from config.settings import settings

console = Console()


def _save_test_cases(tests: list[dict], ts: str) -> Path | None:
    """Lưu generated test cases ra thư mục test_cases/."""
    if not tests:
        return None
    settings.test_cases_dir.mkdir(parents=True, exist_ok=True)
    path = settings.test_cases_dir / f"generated_{ts}.json"
    path.write_text(json.dumps(tests, ensure_ascii=False, indent=2), encoding="utf-8")
    return path


def _build_markdown_report(
    request: str,
    plan: dict,
    execution: dict,
    tests_count: int,
    test_cases_path: str | None,
) -> str:
    lines = [
        f"# QC Agent Report",
        f"",
        f"**Thời gian:** {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}",
        f"**Request:** {request}",
        f"**Test Plan:** {plan.get('title', 'N/A')}",
        f"**Scope:** {plan.get('scope', 'api')}",
        f"",
        f"## Tóm tắt kết quả",
        f"",
        f"| Metric | Value |",
        f"|--------|-------|",
        f"| Total | {execution.get('total', 0)} |",
        f"| Passed | {execution.get('passed', 0)} |",
        f"| Failed | {execution.get('failed', 0)} |",
        f"| Error | {execution.get('error', 0)} |",
        f"| Skipped | {execution.get('skipped', 0)} |",
        f"| Duration (ms) | {execution.get('duration_ms', 0)} |",
        f"| Generated tests | {tests_count} |",
        f"",
    ]

    fails = [d for d in execution.get("details", []) if d.get("status") in ("failed", "error")]
    if fails:
        lines.append("## Chi tiết lỗi")
        lines.append("")
        for f in fails:
            lines.append(f"- **{f.get('id')}** – {f.get('title')}: {f.get('error_message')}")
        lines.append("")

    if test_cases_path:
        lines.append(f"**Test cases file:** `{test_cases_path}`")
        lines.append("")

    lines.append("---")
    lines.append("*Generated by QC Agent Phase 1*")
    return "\n".join(lines)


def reporter_node(state: AgentState) -> dict[str, Any]:
    """Node: in summary + lưu report JSON + Markdown + test cases."""
    execution = state.get("execution_result") or {}
    plan = state.get("test_plan") or {}
    request = state.get("user_request", "")
    tests = state.get("generated_tests") or []

    # --- Terminal summary ---
    table = Table(title="QC Agent – Kết quả chạy test", show_header=True, header_style="bold magenta")
    table.add_column("Metric", style="cyan")
    table.add_column("Value", style="green")

    table.add_row("Total", str(execution.get("total", 0)))
    table.add_row("Passed", str(execution.get("passed", 0)))
    table.add_row("Failed", str(execution.get("failed", 0)))
    table.add_row("Error", str(execution.get("error", 0)))
    table.add_row("Skipped", str(execution.get("skipped", 0)))
    table.add_row("Duration (ms)", str(execution.get("duration_ms", 0)))

    console.print()
    console.print(table)

    fails = [d for d in execution.get("details", []) if d.get("status") in ("failed", "error")]
    if fails:
        console.print("\n[bold red]Chi tiết lỗi:[/bold red]")
        for f in fails:
            console.print(f"  • {f.get('id')} – {f.get('title')}: {f.get('error_message')}")

    # --- Lưu files ---
    settings.reports_dir.mkdir(parents=True, exist_ok=True)
    ts = datetime.now().strftime("%Y%m%d_%H%M%S")

    # 1. Lưu generated test cases
    tc_path = _save_test_cases(tests, ts)
    if tc_path:
        console.print(f"\n[dim]Saved test cases → {tc_path}[/dim]")

    # 2. Report JSON
    report_json_path = settings.reports_dir / f"report_{ts}.json"
    report_data = {
        "timestamp": ts,
        "user_request": request,
        "test_plan": {
            "title": plan.get("title"),
            "summary": plan.get("summary"),
            "scope": plan.get("scope"),
            "risks": plan.get("risks"),
        },
        "execution_result": execution,
        "generated_tests_count": len(tests),
        "test_cases_file": str(tc_path) if tc_path else None,
    }
    report_json_path.write_text(json.dumps(report_data, ensure_ascii=False, indent=2), encoding="utf-8")

    # 3. Report Markdown
    report_md_path = settings.reports_dir / f"report_{ts}.md"
    md_content = _build_markdown_report(
        request=request,
        plan=plan,
        execution=execution,
        tests_count=len(tests),
        test_cases_path=str(tc_path) if tc_path else None,
    )
    report_md_path.write_text(md_content, encoding="utf-8")

    summary = (
        f"Đã chạy {execution.get('total', 0)} test case. "
        f"Passed: {execution.get('passed', 0)}, "
        f"Failed: {execution.get('failed', 0)}, "
        f"Error: {execution.get('error', 0)}. "
        f"\nReport JSON: {report_json_path}"
        f"\nReport MD  : {report_md_path}"
    )
    if tc_path:
        summary += f"\nTest cases : {tc_path}"

    console.print(Panel(summary, title="[bold green]Hoàn thành[/bold green]", border_style="green"))

    return {
        "report_path": str(report_json_path),
        "final_summary": summary,
        "current_step": "reporter_done",
        "error": None,
    }
